ocupacion=Ocupaci\u00f3n :
convocatoria=XV Universidad de Verano de Anticapitalista
nomape=Nombre y apellidos
dni=DNI, NIE o pasaporte :
edad=Edad :
residencia=Ciudad de Residencia :
email=Correo electr\u00f3nico :
telefono=Tel\u00e9fono:
ccaa=Comunidad Aut\u00f3noma
estancia=Tipo de estancia :
tarifa=Tipo de tarifa :
orientacion_alimentaria= Orientaci\u00f3n alimentaria :
sindicato=\u00bfPerteneces a alg\u00fan sindicato? 
sindicato1=\u00bfQue sindicato?
organizacion=\u00bfPerteneces a alguna organizaci\u00f3n? 
guarderia=\u00bfNecesitar\u00e1s servicio de ludoteca?   
guarderia1=\u00bfQue edad tiene el ni\u00f1o/ni\u00f1a?
guarderia2=N\u00famero de DNI del tutor
observaciones=Observaciones
alergias=Indicanos si tienes alergias, problemas de movilidad u otras necesidades especiales
transferencia1=La inscripci\u00f3n solo se habr\u00e1 completado efectivamente cuando veas en la siguiente
transferencia2=pantalla un mensaje informando del n\u00famero de matricula que te hemos asignado
consentimiento1=Los datos personales que solicitamos ser\u00e1n utilizados exclusivemente para la organizaci\u00f3n de la Universidad de Verano de Anticapitalistas.
consentimiento2= Tu consentimiento es necesario para el tratamiento posterior. Los datos personales se conservar\u00e1n por espacio no superior a un a\u00f1o. 
consentimiento3=Puedes solicitar la cancelaci\u00f3n o modificaci\u00f3n de los datos enviando un mensaje a la direcci\u00f3n de correo universidadverano@anticapitalistas.org
consentimiento4=Doy mi consentimiento
dia1=Martes 26
dia2=Mi\u00e9rcoles 27
dia3=Jueves 28
dia4=Viernes 29
dia5=S\u00e1bado 30
ocupacion1=\u00bfQue otra ocupaci\u00f3n?
organizacion1=\u00bfQue organizaci\u00f3n?
confirmacion=Su solicitud de inscripci\u00f3n ha sido recibida. En breve recibir\u00e1 un mensaje de correo electr\u00f3nico
tarifa_l1= Estancia completa litera
tarifa_l2= Estancia completa estudiante/parad@ en litera
tarifa_l3= Estancia completa ni\u00f1@ de 1 a 12 a\u00f1os en litera
tarifa_l4=D\u00eda completo litera
tarifa_l5=D\u00eda completo estudiante/parad@ en litera
tarifa_l6=D\u00eda completo ni\u00f1@ de 1 a 12 a\u00f1os en litera
tarifa_l7=Estancia completa en tienda
tarifa_l8=Estancia completa en tienda estudiante/parad@
tarifa_l9=Estancia completa ni\u00f1@s de 1 a 12 a\u00f1os en tienda
tarifa_l10=D\u00eda completo tienda
tarifa_l11=D\u00eda completo tienda estudiante/parad@
tarifa_l12=D\u00eda completo ni\u00f1@ de 1 a 12 a\u00f1os en tienda
tarifa_l13=Beb\u00e9s de 0 a 12 meses
tarifa_l14= Los d\u00edas completos incluyen las tres comidas. No se contemplan fracciones de d\u00eda. El martes 23 incluye comida y cena y el domingo 28 solo desayuno. 
tarifa_m1= Una vez completada la inscripci\u00f3n recibir\u00e1s un correo electr\u00f3nico a la direcci\u00f3n que hayas indicado en el formulario con el n\u00famero de referencia que tienes NO TE OLVIDES PONER EN EL CONCEPTO ' UNI + N\u00daMERO O N\u00daMEROS DE REFERENCIA'. Si lo prefieres puedes abonar el importe total en la transferencia. IMPORTANTE: la reserva no se har\u00e1 efectiva hasta que se efect\u00fae el ingreso de la se\u00f1al. S\u00f3lo se devolver\u00e1 esta suma en casos de fuerza mayor justificados y no m\u00e1s tarde de una semana antes del inicio de la Universidad.
tarifa_m2= Para cualquier duda o consulta puedes contactarnos  enviando un correo a universidadverano@anticapitalistas.org
tarifa_m3= Para finalizar la inscripci\u00f3n escribe el texto que aparece m\u00e1s y pulsa el bot\u00f3n 'Inscribirse'
tarifa_m4= Para completar la inscripci\u00f3n necesitamos una se\u00f1al del 50% del importe de la inscripci\u00f3n,
tarifa_m5= el resto puedes abonarlo presencialmente al comienzo de la Universidad 
tarifa_m6= Tambien puedes abonar anticipadamente el coste integro 
tarifa_m7= La cuenta bancaria bancaria donde debes hacer el ingreso es: 
tarifa_m8= Notas informativas importantes:
tarifa_m9= Si tienes papeles (DNI, pasaporte) no olvides tra\u00e9rtelos contigo por si hay visitas.
tarifa_m10= No te olvides tampoco traer la tarjeta sanitaria.
tarifa_m14=Apertura de inscripciones a partir del 15 de mayo 
tarifa_m15=Puedes consultar el programa en este enlace
tarifa_h1= Tipo de estancia
tarifa_h2= Con inscripci\u00f3n anterior al 1 de julio
tarifa_h3= Con inscripci\u00f3n posterior al 1 de julio
tarifa_h4= Inscripci\u00f3n de apoyo
tarifa_h5= Sin inscripci\u00f3n
tarifa_m11=Debes matricular separadamente al ni\u00f1o y al adulto. En la inscripci\u00f3n del ni\u00f1o debes poner el DNI del tutor
tarifa_m12=Beneficiario: Asociaci\u00f3n Anticapitalistas
tarifa_m13=Puedes consultar el programa en este enlace
vacunacion=Estado vacunaci\u00f3n COVID-19
email2= Repite el correo electr\u00f3nico :
alergias2=\u00bfCu\u00e1les?
colabora=\u00bfDeseas colaborar en las actividades? 
lanzadera=\u00bfNecesitar\u00e1s servicio de lanzadera?
dias=\u00bfQue d\u00edas?
importe=Importe de la opci\u00f3n seleccionada
button_inscripcion=Inscribirse
confirmacion1=El n\u00famero de inscripci\u00f3n que debes hacer constar en la transferencia es \u0020 \u0020
confirmacion2=El total a pagar es de \u0020 \u0020
paypal=Si lo deseas, pues pagar ahora el importe de la inscripci\u00f3n a trav\u00e9s de PayPal
IBAN=ES1015500001250021715826  Titular Asociaci\u00f3n Anticapitalistas - Movimiento por el Poder popular
entorno=servidor
path1=/home/ec2-user/glassfish4/glassfish/domains/domain1/applications/WebUniVerano/ficheros/
path2=C:\\Users\\INAEM-2\\Documents\\NetBeansProjects\\WebUniVerano\\web\\ficheros\\
fecha_limite=01/07/2025
mens_confirmacion1=Tu inscripci\u00f3n se ha realizado correctamente, tienes que indicar este n\u00famero en la transferencia bancaria:
mens_confirmacion2=Adjunto al presente mensaje te enviamos un fichero pdf con informaci\u00f3n de inter\u00e9s sobre la
mens_confirmacion3=La cuenta bancaria donde debes hacer el ingreso es:
mens_confirmacion4=Si tienes papeles (DNI, pasaporte) no olvides tra\u00e9rtelos contigo, no te olvides tampoco traer la tarjeta sanitaria.
mens_confirmacion5=.El importe total de la inscripci\u00f3n, salvo error u omisi\u00f3n, es de
lanzadera2=*Ver condiciones de uso en la web 
lanzadera3=https://unianticapi.info/lanzadera